services:

  dip-backend:
    build: ./backend
    container_name: dip_backend
    ports:
      - "8000:8000"
    volumes:
      - ./data:/data
      - ./.cache:/root/.cache

    environment:
      - TRANSFORMERS_OFFLINE=1
      - HF_HUB_OFFLINE=1

    depends_on:
      - qdrant
      - gotenberg

  dip-frontend:
    build: ./DIP_frontend
    container_name: dip_frontend
    ports:
      - "8003:8003"
    depends_on:
      - dip-backend

  ip-backend:

    build: ./IP_backend
    container_name: ip_backend
    ports:
      - "8001:8001"

    volumes:
      - ./.cache:/root/.cache  

    environment:
      - TRANSFORMERS_OFFLINE=1
      - HF_HUB_OFFLINE=1
    depends_on:
      - qdrant
      - ollama
      - ollama-warmup

  ip-frontend:

    build: ./IP_frontend
    container_name: ip_frontend
    ports:
      - "8002:8002"

    depends_on:
      - ip-backend

  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant_db
    ports:
      - "6333:6333"
    volumes:
      - ./vector_store/qdrant:/qdrant/storage

  gotenberg:
    image: gotenberg/gotenberg:7
    container_name: gotenberg
    ports:
      - "3000:3000"

  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - "./models/OLLAMA model:/root/.ollama"
    deploy:
      resources:
        reservations: 
          devices:
            - driver: nvidia
              device_ids: ['0']
              capabilities: [gpu]
    environment:
      - OLLAMA_FLASH_ATTENTION=1
      - OLLAMA_NUM_GPU=-1
      - OLLAMA_KEEP_ALIVE=-1
    restart: unless-stopped
 
  ollama-warmup:
    image: curlimages/curl:latest
    container_name: ollama_warmup
    depends_on: 
      - ollama

    command: >
      sh -c "sleep 5 && curl -X POST http://ollama:11434/api/generate -d '{\"model\": \"Refinery_LLM\"}'"

  


